#
# Use this configuration with WireGuard client
#
[Interface]
Address = 10.14.0.2/16
PrivateKey = gFkU2xL65zagdE8sjaas/296lEG0UV7mSsZX2Vksx1Y=
DNS = 162.252.172.57, 149.154.159.92
[Peer]
PublicKey = 6dZGkg0iAMgQuOCGknAgBAqDEeJeBQ4Of5eblO4aNC8=
AllowedIPs = 0.0.0.0/0
Endpoint = ae-dub.prod.surfshark.com:51820