#
# Use this configuration with WireGuard client
#
[Interface]
Address = 10.14.0.2/16
PrivateKey = gFkU2xL65zagdE8sjaas/296lEG0UV7mSsZX2Vksx1Y=
DNS = 162.252.172.57, 149.154.159.92
[Peer]
PublicKey = peDjRPEdHHmo0hGootZ9f+MQCEXmziFkLhMTl2PeXRM=
AllowedIPs = 0.0.0.0/0
Endpoint = dk-cph.prod.surfshark.com:51820